create table if not exists public.vendors (
  id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.handle_new_vendor_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.vendors (id)
  values (new.id)
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_vendor_user();

create table if not exists public.applicants (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  vendor_id uuid not null references public.vendors (id) on delete restrict,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  dob date,
  country_of_birth text,
  country_of_citizenship text,
  a_number text,
  uscis_online_account_number text,
  passport_number text,
  passport_country text,
  entry_date_us date,
  i94_number text,
  current_status text,
  flow_type text not null,
  flow_answers jsonb not null default '{}'::jsonb,
  constraint applicants_flow_type_check
    check (flow_type in ('TPS', 'TPS_EAD', 'ASYLUM_EAD')),
  constraint applicants_email_not_blank
    check (length(trim(email)) > 0),
  constraint applicants_first_name_not_blank
    check (length(trim(first_name)) > 0),
  constraint applicants_last_name_not_blank
    check (length(trim(last_name)) > 0)
);
